services:
  mongo:
    image: mongo:7
    container_name: cipherchat-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - cipherchat_mongodata:/data/db

volumes:
  cipherchat_mongodata:
